import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy';

const isProd = process.env.BUILD === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

// const outDir = `dist`
// Hack: To generate all output directly into an obsidian vault for testing:
const outDir = `../plugin-playground/.obsidian/plugins/obsidian-marp-presentations`;

export default {
	input: 'main.ts',
	output: {
		dir: outDir,
		sourcemap: 'inline',
		sourcemapExcludeSources: isProd,
		format: 'cjs',
		exports: 'default',
		banner,
	},
	external: ['obsidian'],
	plugins: [
		typescript(),
		nodeResolve({ browser: true }),
		commonjs(),
		copy({
			targets: [
				{ src: 'manifest.json', dest: outDir },
				{ src: 'styles.css', dest: outDir },
				{ src: 'versions.json', dest: outDir },
				{ src: 'README.md', dest: outDir },
			],
		}),
	],
};
